[workflow]
access_level = 'full'
datset = 'prophecy'
datasets = ['prophecy']
keep_scratch = true
skip_samples_with_missing_input = true
check_expected_outputs = true

[hail]
hail_pool_label = 'large-cohort'
