namespace: main
analysis_dataset: seqr
# skip_datasets: ['flinders-ophthal']
datasets: ['ohmr4-epilepsy']
skip_samples: [
  CPG11783,   # acute-care, no FASTQ data
#  CPG12310,   # acute-care
#  CPG199679,  # acute-care
  CPG13326,   # perth-neuro, no FASTQ data: https://github.com/populationgenomics/seqr-private/issues/2
  CPG200014,  # perth-neuro, https://centrepopgen.slack.com/archives/C01R7CKJGHM/p1654038000773069
]
check_inputs: true
skip_samples_with_missing_input: false
keep_scratch: true
status_reporter: cpg
slack_channel: 'seqr-loader'
cram_qc: false
sequencing_type: genome
realign_from_cram_version: 'bwamem'
hail_pool_label: seqr
#skip_samples_stages:
#  VerifyBamId: [CPG13409]  # https://batch.hail.populationgenomics.org.au/batches/56236/jobs/372
