[workflow]
first_stage = 'Align'
last_stage = 'GenotypeSample'
access_level = 'full'
dataset = 'seqr'
datasets = [
#    'acute-care',
    'perth-neuro',
#    'ravenscroft-rdstudy',
#    'circa',
#    'heartkids',
#    'ohmr3-mendelian',
#    'ohmr4-epilepsy',
#    'rdnow',
#    'mito-disease',
#    'ravenscroft-arch',
#    'hereditary-neuro',
#    'validation',
#    'schr-neuro',
#    'ibmdx',
#    'mcri-lrp',
#    'kidgen',
#    'ag-hidden'
]
#create_es_index_for_datasets = ['schr-neuro']
#status_reporter = 'smdb'
skip_samples = [
    'CPG11783',   # acute-care, no FASTQ data
]
check_inputs = true
skip_samples_with_missing_input = false
keep_scratch = true
sequencing_type = 'genome'
dataset_gcp_project = 'seqr-308602'
jc_intervals_num = 200
vep_intervals_num = 200
check_intermediates = true
dry_run = false

[workflow.skip_samples_stages]
VerifyBamId = ['CPG13409']  # https://batch.hail.populationgenomics.org.au/batches/56236/jobs/372

[hail]
pool_label = 'seqr'
billing_project = 'seqr'

[slack]
channel = 'seqr-loader-test'
token_secret_id = 'slack-seqr-loader-token'
token_project_id = 'seqr-308602'

[references]
liftover_38_to_37 = 'liftover/grch38_to_grch37.over.chain.gz'

[images]
hail = 'driver:18a44866a0c70017f8ab6880f94572e22b2a5b36-hail-51b96aef4671a9985d2c7f69eb370de83738ff6e'
sm-api = 'driver:18a44866a0c70017f8ab6880f94572e22b2a5b36-hail-51b96aef4671a9985d2c7f69eb370de83738ff6e'
