[workflow]
access_level = 'full'
dataset = 'seqr'
datasets = [
    'acute-care', 
    'perth-neuro', 
    'ravenscroft-rdstudy', 
    'circa', 
    'heartkids',
    'ohmr3-mendelian',
    'ohmr4-epilepsy',
    'rdnow',
    'mito-disease',
    'ravenscroft-arch',
    'hereditary-neuro',
]
add_validation_dataset = true
#status_reporter = 'smdb'
skip_samples = [
  'CPG11783',   # acute-care, no FASTQ data
  'CPG13326',   # perth-neuro, no FASTQ data: https://github.com/populationgenomics/seqr-private/issues/2
]
check_inputs = true
skip_samples_with_missing_input = false
keep_scratch = true
sequencing_type = 'genome'
dataset_gcp_project = 'seqr-308602'
jc_intervals_num = 200

[workflow.skip_samples_stages]
VerifyBamId = ['CPG13409']  # https://batch.hail.populationgenomics.org.au/batches/56236/jobs/372

[hail]
pool_label = 'seqr'
billing_project = 'seqr'
bucket = 'gs://cpg-seqr-hail'

[slack]
channel = 'seqr-loader-test'
token_secret_id = 'slack-seqr-loader-token'
token_project_id = 'seqr-308602'

[references]
liftover_38_to_37 = 'liftover/grch38_to_grch37.over.chain.gz'
