namespace: main
analysis_dataset: seqr
datasets: ['acute-care', 'circa', 'perth-neuro', 'heartkids', 'ravenscroft-rdstudy']
skip_samples: [CPG11783,CPG12310,CPG199679,CPG13326]  # acute-care,acute-care,acute-care,perth-neuro
create_es_index_for_datasets: ['acute-care']  # ['circa', 'perth-neuro', 'heartkids', 'ravenscroft-rdstudy']
keep_scratch: true
skip_samples_with_missing_input: false
ped_checks: false
version: v0
status_reporter_type: cpg
slack_channel: seqr-loader-test
