[workflow]
access_level = 'full'
dataset = 'seqr'
datasets = [
    'acute-care',
    'perth-neuro',
    'ravenscroft-rdstudy',
    'circa',
    'heartkids',
    'ohmr3-mendelian',
    'ohmr4-epilepsy',
    'rdnow',
    'mito-disease',
    'ravenscroft-arch',
    'hereditary-neuro',
    'validation',
    'schr-neuro',
    'ibmdx',
    'mcri-lrp',
    'kidgen',
    'ag-hidden',
    'flinders-ophthal',
]
#create_es_index_for_datasets = ['schr-neuro']
#status_reporter = 'smdb'
skip_samples = [
    'CPG11783',   # acute-care, no FASTQ data
    'CPG246645',  # ag-hidden, eof issue  https://batch.hail.populationgenomics.org.au/batches/97645/jobs/440
    'CPG246678',  # ag-hidden, diff fastq size  https://batch.hail.populationgenomics.org.au/batches/97645/jobs/446
]
check_inputs = true
keep_scratch = true
sequencing_type = 'genome'
dataset_gcp_project = 'seqr-308602'
jc_intervals_num = 200
vep_intervals_num = 200
check_intermediates = true
dry_run = false
realign_from_cram_version = 'bwamem'

[workflow.cram_version_reference]
bwamem = 'gs://cpg-reference/hg38/v0/Homo_sapiens_assembly38.fasta'

[workflow.skip_samples_stages]
VerifyBamId = ['CPG13409']  # https://batch.hail.populationgenomics.org.au/batches/56236/jobs/372

[hail]
pool_label = 'seqr'
billing_project = 'seqr'

[slack]
channel = 'seqr-loader-test'
token_secret_id = 'slack-seqr-loader-token'
token_project_id = 'seqr-308602'

[references]
liftover_38_to_37 = 'liftover/grch38_to_grch37.over.chain.gz'

[images]
hail = 'driver:5d04b6d6bb411ea4b8750f40cf39fd0b701ea288-hail-c4eb2b16220d9872f417412ea565902f78739124'
sm-api = 'driver:5d04b6d6bb411ea4b8750f40cf39fd0b701ea288-hail-c4eb2b16220d9872f417412ea565902f78739124'
