[workflow]
access_level = 'full'
dataset = 'seqr'
datasets = ['perth-neuro']
#datasets = [
#    'acute-care', 
#    'perth-neuro', 
#    'ravenscroft-rdstudy', 
#    'circa', 
#    'heartkids',
#    'ohmr3-mendelian', 
#    'ohmr4-epilepsy',
#    'rdnow',
#    'mito-disease',
#    'ravenscroft-arch',
#    'hereditary-neuro',
#]
only_samples = ['CPG13409']
skip_samples = [
  'CPG11783',   # acute-care, no FASTQ data
  'CPG13326',   # perth-neuro, no FASTQ data: https://github.com/populationgenomics/seqr-private/issues/2
#  'CPG200014',  # heartkids, https://centrepopgen.slack.com/archives/C01R7CKJGHM/p1654038000773069
]
check_inputs = true
skip_samples_with_missing_input = true
keep_scratch = true
status_reporter = 'smdb'
#skip_samples_stages:
#  VerifyBamId: [CPG13409]  # https://batch.hail.populationgenomics.org.au/batches/56236/jobs/372
sequencing_type = 'genome'
dataset_gcp_project = 'seqr-308602'

[seqr]
password_secret_id = 'seqr-es-password'
password_project_id = 'seqr-308602'

[hail]
pool_label = 'seqr'
billing_project = 'seqr'
bucket = 'gs://cpg-seqr-hail'

[slack]
channel = 'seqr-loader-test'
token_secret_id = 'slack-seqr-loader-token'
token_project_id = 'seqr-308602'
