namespace: main
analysis_dataset: seqr
input_datasets: [acute-care,perth-neuro,heartkids,ravenscroft-rdstudy,circa]
skip_samples: [CPG11783,CPG11783,CPG13326,CPG200576,CPG200469]
keep_scratch: true
skip_samples_with_missing_input: true
validate_smdb_analyses: false
make_seqr_metadata: true
first_stage: AnnotateCohortStage
ped_checks: false
version: v0
