[workflow]
name = 'align_and_genotype'
description = 'Aligns and genotypes the gVCFs from the individual sequencing groups'

status_reporter = 'metamist'

[cramqc]
assume_sorted = true
num_pcs = 4

[qc_thresholds.genome.min]
"MEDIAN_COVERAGE" = 10
"PCT_PF_READS_ALIGNED" = 0.80
[qc_thresholds.genome.max]
"FREEMIX" = 0.04
"PERCENT_DUPLICATION" = 25

[slack]
channel = 'workflows-qc'
token_secret_id = 'slack-seqr-loader-token'
token_project_id = 'seqr-308602'
