[workflow]

# The name of the workflow
name = "echtvar"

# the cohort isn't important, so this is a dummy value
input_cohorts = ['COH2142']
sequencing_type = 'genome'

[ensembl]
#bed_file = "gs://cpg-common-test-analysis/reannotation/ensembl_113.bed"
bed_file = "gs://cpg-common-test-analysis/reannotation/ensembl_113_merged.bed"