[workflow]

# The name of the workflow
name = "echtvar"

input_cohorts = ['COH2142']

sequencing_type = 'genome'

[images]
echtvar = 'australia-southeast1-docker.pkg.dev/cpg-common/images-dev/echtvar:v0.2.1'
