[workflow]
'nothing' = 'here'

status_reporter = 'metamist'

# attributes to provision the Exomiser VMs
exomiser_memory = '60Gi'
exomiser_storage = '200Gi'
exomiser_cpu = 4

# number of exomiser jobs to fit onto each VM
exomiser_chunk_size = 8

# number of jobs to run in parallel through backgrounded processes
exomiser_parallel_chunks = 4

# should probably add some exome/genome defaults here to alter behaviour/regions
