[workflow]
name = 'gatk_sv'
dataset_gcp_project = 'seqr-308602'
dataset = 'seqr'

[images]
cnmops_docker = 'australia-southeast1-docker.pkg.dev/cpg-common/images/sv/cnmops:2022-06-10-v0.23-beta-9c6fbf56'
condense_counts_docker = 'australia-southeast1-docker.pkg.dev/cpg-common/images/sv/gatk:4.2.6.1-36-g88b0578'
gatk_docker = 'australia-southeast1-docker.pkg.dev/cpg-common/images/sv/gatk:4.2.6.1-36-g88b0578'
gatk_docker_pesr_override = 'australia-southeast1-docker.pkg.dev/cpg-common/images/sv/gatk:4.2.6.1-36-g88b0578'
genomes_in_the_cloud_docker = 'australia-southeast1-docker.pkg.dev/cpg-common/images/sv/genomes-in-the-cloud:2.3.2-1510681135'
linux_docker = 'australia-southeast1-docker.pkg.dev/cpg-common/images/sv/ubuntu1804'
manta_docker = 'australia-southeast1-docker.pkg.dev/cpg-common/images/sv/manta:8645aa'
scramble_docker = 'australia-southeast1-docker.pkg.dev/cpg-common/images/sv/scramble:1.0.2'
samtools_cloud_docker = 'australia-southeast1-docker.pkg.dev/cpg-common/images/sv/samtools-cloud:2022-06-10-v0.23-beta-9c6fbf56'
sv_base_docker = 'australia-southeast1-docker.pkg.dev/cpg-common/images/sv/sv-base:2022-06-10-v0.23-beta-9c6fbf56'
sv_base_mini_docker = 'australia-southeast1-docker.pkg.dev/cpg-common/images/sv/sv-base-mini:2022-06-10-v0.23-beta-9c6fbf56'
sv_pipeline_base_docker = 'australia-southeast1-docker.pkg.dev/cpg-common/images/sv/sv-pipeline:2022-08-08-v0.24-beta-79d76bc9'
sv_pipeline_docker = 'australia-southeast1-docker.pkg.dev/cpg-common/images/sv/sv-pipeline:2022-08-08-v0.24-beta-79d76bc9'
sv_pipeline_hail_docker = 'australia-southeast1-docker.pkg.dev/cpg-common/images/sv/sv-pipeline:2022-08-08-v0.24-beta-79d76bc9'
sv_pipeline_updates_docker = 'australia-southeast1-docker.pkg.dev/cpg-common/images/sv/sv-pipeline:2022-08-08-v0.24-beta-79d76bc9'
sv_pipeline_qc_docker = 'australia-southeast1-docker.pkg.dev/cpg-common/images/sv/sv-pipeline:2022-08-08-v0.24-beta-79d76bc9'
sv_pipeline_rdtest_docker = 'australia-southeast1-docker.pkg.dev/cpg-common/images/sv/sv-pipeline:2022-08-08-v0.24-beta-79d76bc9'
wham_docker = 'australia-southeast1-docker.pkg.dev/cpg-common/images/sv/wham:8645aa'
igv_docker = 'australia-southeast1-docker.pkg.dev/cpg-common/images/sv/igv:mw-xz-fixes-2-b1be6a9'
duphold_docker = 'australia-southeast1-docker.pkg.dev/cpg-common/images/sv/duphold:mw-xz-fixes-2-b1be6a9'
vapor_docker = 'australia-southeast1-docker.pkg.dev/cpg-common/images/sv/vapor:header-hash-2fc8f12'
cloud_sdk_docker = 'australia-southeast1-docker.pkg.dev/cpg-common/images/sv/cloud-sdk'
pangenie_docker = 'australia-southeast1-docker.pkg.dev/cpg-common/images/sv/pangenie:vj-127571f'
sv-base-virtual-env = 'australia-southeast1-docker.pkg.dev/cpg-common/images/sv/sv-base-virtual-env:2022-06-10-v0.23-beta-9c6fbf56'
cnmops-virtual-env = 'australia-southeast1-docker.pkg.dev/cpg-common/images/sv/cnmops-virtual-env:2022-06-10-v0.23-beta-9c6fbf56'
sv-pipeline-virtual-env = 'australia-southeast1-docker.pkg.dev/cpg-common/images/sv/sv-pipeline-virtual-env:2022-06-10-v0.23-beta-9c6fbf56'
samtools-cloud-virtual-env = 'australia-southeast1-docker.pkg.dev/cpg-common/images/sv/samtools-cloud-virtual-env:2022-06-10-v0.23-beta-9c6fbf56'
sv_utils_docker = 'australia-southeast1-docker.pkg.dev/cpg-common/images/sv/sv-utils:805d18b'
gq_recalibrator_docker = 'australia-southeast1-docker.pkg.dev/cpg-common/images/sv/gatk:93d635a7ea'

[references.broad]
unpadded_intervals_file = 'hg38.even.handcurated.20k.intervals'

[references.broad.sv.resources]
prefix = 'sv-resources/resources/v1'
wham_include_list_bed_file = 'wham_whitelist.bed'
primary_contigs_list = 'primary_contigs.list'
primary_contigs_fai = 'contig.fai'
preprocessed_intervals = 'preprocessed_intervals.interval_list'
manta_region_bed = 'primary_contigs_plus_mito.bed.gz'
melt_standard_vcf_header = 'melt_standard_vcf_header.txt'
genome_file = 'hg38.genome'
wgd_scoring_mask = 'wgd_scoring_mask.hg38.gnomad_v3.bed'
allosomal_contigs = 'allosome.fai'
contig_ploidy_priors = 'hg38.contig_ploidy_priors_homo_sapiens.tsv'
inclusion_bed = 'hg38_primary_contigs.bed'
autosome_file = 'autosome.fai'
allosome_file = 'allosome.fai'
cnmops_exclude_list = 'GRCh38_Nmask.bed'
cytoband = 'cytobands_hg38.bed.gz'
mei_bed = 'mei_hg38.bed.gz'
rmsk = 'hg38.randomForest_blacklist.withRepMask.bed.gz'
segdups = 'hg38.SD_gaps_Cen_Tel_Heter_Satellite_lumpy.blacklist.sorted.merged.bed.gz'
seed_cutoffs = 'seed_cutoff.txt'
pesr_exclude_list = 'PESR.encode.peri_all.repeats.delly.hg38.blacklist.sorted.bed.gz'
depth_exclude_list = 'depth_blacklist.sorted.bed.gz'
bin_exclude = 'bin_exclude.hg38.gatkcov.bed.gz'
empty_file = 'empty.file'
protein_coding_gtf = 'gs://gatk-sv-resources-public/hg38/v0/sv-resources/resources/v1/MANE.GRCh38.v0.95.select_ensembl_genomic.gtf'

[references.broad.sv.ref_panel]
prefix = 'sv-resources/ref-panel'
ped_file = '1KG/v1/ped/1kg_ref_panel_v1.ped'
clean_vcf = '1KG/v1/calls/ref_panel_1kg_v1.cleaned.vcf.gz'
ref_panel_bincov_matrix = '1KG/v1/merged_evidence/ref_panel_1kg_v1.bincov.bed.gz'
qc_definitions = '1KG/v2/single_sample.qc_definitions.tsv'
contig_ploidy_model_tar = '1KG/v2/gcnv/ref_panel_1kg_v2-contig-ploidy-model.tar.gz'
model_tar_tmpl = '1KG/v2/gcnv/model_files/ref_panel_1kg_v2-gcnv-model-shard-{shard}.tar.gz'
ref_panel_PE_file_tmpl = 'tws_SVEvidence/pe/{sample}.pe.txt.gz'
ref_panel_SR_file_tmpl = 'tws_SVEvidence/sr/{sample}.sr.txt.gz'
ref_panel_SD_file_tmpl = 'tws_SVEvidence/sd/{sample}.sd.txt.gz'

[sv_ref_panel]
ref_panel_samples = ['HG00096', 'HG00129', 'HG00140', 'HG00150', 'HG00187', 'HG00239', 'HG00277', 'HG00288', 'HG00337', 'HG00349', 'HG00375', 'HG00410', 'HG00457', 'HG00557', 'HG00599', 'HG00625', 'HG00701', 'HG00740', 'HG00844', 'HG01060', 'HG01085', 'HG01112', 'HG01275', 'HG01325', 'HG01344', 'HG01356', 'HG01384', 'HG01393', 'HG01396', 'HG01474', 'HG01507', 'HG01572', 'HG01607', 'HG01709', 'HG01747', 'HG01790', 'HG01794', 'HG01799', 'HG01861', 'HG01874', 'HG01880', 'HG01885', 'HG01958', 'HG01982', 'HG02002', 'HG02010', 'HG02019', 'HG02020', 'HG02069', 'HG02085', 'HG02186', 'HG02221', 'HG02235', 'HG02272', 'HG02275', 'HG02299', 'HG02332', 'HG02367', 'HG02374', 'HG02489', 'HG02490', 'HG02491', 'HG02586', 'HG02588', 'HG02611', 'HG02620', 'HG02642', 'HG02648', 'HG02658', 'HG02855', 'HG02953', 'HG03007', 'HG03009', 'HG03085', 'HG03099', 'HG03100', 'HG03111', 'HG03369', 'HG03370', 'HG03436', 'HG03449', 'HG03472', 'HG03476', 'HG03556', 'HG03604', 'HG03649', 'HG03684', 'HG03694', 'HG03709', 'HG03722', 'HG03727', 'HG03744', 'HG03756', 'HG03789', 'HG03850', 'HG03864', 'HG03872', 'HG03888', 'HG04118', 'HG04158', 'HG04161', 'HG04183', 'NA06984', 'NA10847', 'NA11894', 'NA12340', 'NA12489', 'NA12872', 'NA18499', 'NA18507', 'NA18530', 'NA18539', 'NA18549', 'NA18553', 'NA18560', 'NA18638', 'NA18923', 'NA18941', 'NA18945', 'NA18956', 'NA18995', 'NA19001', 'NA19035', 'NA19062', 'NA19102', 'NA19143', 'NA19184', 'NA19350', 'NA19351', 'NA19377', 'NA19443', 'NA19449', 'NA19661', 'NA19678', 'NA19679', 'NA19684', 'NA19746', 'NA19795', 'NA19818', 'NA19913', 'NA20126', 'NA20320', 'NA20321', 'NA20346', 'NA20509', 'NA20510', 'NA20522', 'NA20752', 'NA20764', 'NA20802', 'NA20845', 'NA20869', 'NA20895', 'NA21102', 'NA21122', 'NA21133']
model_tar_cnt = 285
