[workflow]
name = 'gatk_sv'
dataset_gcp_project = 'seqr-308602'
dataset = 'seqr'
ref_fasta = 'gs://cpg-common-main/references/hg38/v0/dragen_reference/Homo_sapiens_assembly38_masked.fasta'

[references.gatk_sv]
# This model is trained on the All Of Us dataset. If this is used in any published work,
# credit must be given in accordance with the AoU publication policy.
# Access to this file was provided on a one-off basis, and is not publicly available.
# If an updated model is required, contact Mark Walker at the Broad Institute
aou_filtering_model = 'gs://cpg-common-test/references/gatk-sv/gatk-sv-recalibrator.aou_phase_1.v1.model'

# a couple of annotation arguments are not files
# github.com/broadinstitute/gatk-sv/blob/main/inputs/templates/test/AnnotateVcf/AnnotateVcf.json.tmpl#L4-L8
external_af_population = ['ALL', 'AFR', 'AMR', 'EAS', 'EUR']
external_af_ref_bed_prefix = 'gnomad_v2.1_sv'

# genome tracks are a list of CPG config keys
genome_tracks = [
    'recalibrate_gq_repeatmasker',
    'recalibrate_gq_segmental_dups',
    'recalibrate_gq_simple_reps',
    'recalibrate_gq_umap_s100',
    'recalibrate_gq_umap_s24',
]
genome_tracks_index = [
    'recalibrate_gq_repeatmasker_index',
    'recalibrate_gq_segmental_dups_index',
    'recalibrate_gq_simple_reps_index',
    'recalibrate_gq_umap_s100_index',
    'recalibrate_gq_umap_s24_index',
]
recalibrate_gq_args = [
    '--keep-homvar false',
    '--keep-homref true',
    '--keep-multiallelic true',
    '--skip-genotype-filtering true',
    '--min-samples-to-estimate-allele-frequency -1',
]

# FilterGenotypes - stringent end of [0.3, 0.5] range
fmax_beta = 0.3
