[workflow]
name = 'gatk_sv'
ref_fasta = 'gs://cpg-common-main/references/hg38/v0/dragen_reference/Homo_sapiens_assembly38_masked.fasta'
status_reporter = 'metamist'

# Write dataset MTs for these datasets. Required for the AnnotateDatasetSv stage.
# write_mt_for_datasets = []

# Create Seqr ElasticSearch indices for these datasets. Required for the MtToEsSv stage.
# create_es_index_for_datasets = []

# switches to deactivate all Metrics workflows. We ran into some resourcing issues when our total
# cohort size approached ~1600. Response when raised with GATK team:
#
# "GatherBatchEvidenceMetrics and the other metrics routines at the end of the main workflows are
# primarily for development and testing purposes, so you don’t need to run them as a user"

# these metrics workflows are typically running svtest (https://github.com/broadinstitute/gatk-sv/blob/d37e453038e425acba9683da503218fe3d4b1033/src/svtest/setup.py)
# on each output of the stage, producing output files containing a count/distribution of different variants
# and sizes. The workflow files we are using as Stages do not always capture these results as top-level outputs,
# so we have no reliable method to extract these files into permanent storage.
[resource_overrides.GatherBatchEvidence]
run_matrix_qc = false
run_module_metrics = false

[resource_overrides.ClusterBatch]
run_module_metrics = false

[resource_overrides.GenerateBatchMetrics]
run_module_metrics = false

[resource_overrides.FilterBatch]
run_module_metrics = false

[resource_overrides.GenotypeBatch]
run_module_metrics = false

[resource_overrides.MakeCohortVcf]
run_module_metrics = false

[resource_overrides.FilterGenotypes]
run_qc = false

# if you have to do it, bump the resources
#[resource_overrides.FilterGenotypes.runtime_override_plot_qc_per_family]
#mem_gb = 32

[references.gatk_sv]
# This model is trained on the All Of Us dataset. If this is used in any published work,
# credit must be given in accordance with the AoU publication policy.
# Access to this file was provided on a one-off basis, and is not publicly available.
# If an updated model is required, contact Mark Walker at the Broad Institute
aou_filtering_model = 'gs://cpg-common-test/references/gatk-sv/gatk-sv-recalibrator.aou_phase_1.v1.model'
strvctvre_phylop = 'gs://cpg-common-test/references/hg38.phyloP100way.bw'

# a couple of annotation arguments are not files
# github.com/broadinstitute/gatk-sv/blob/main/inputs/templates/test/AnnotateVcf/AnnotateVcf.json.tmpl#L4-L8
external_af_population = ['ALL', 'AFR', 'AMR', 'EAS', 'EUR']
external_af_ref_bed_prefix = 'gnomad_v2.1_sv'

# genome tracks are a list of CPG config keys
genome_tracks = [
    'recalibrate_gq_repeatmasker',
    'recalibrate_gq_segmental_dups',
    'recalibrate_gq_simple_reps',
    'recalibrate_gq_umap_s100',
    'recalibrate_gq_umap_s24',
]
genome_tracks_index = [
    'recalibrate_gq_repeatmasker_index',
    'recalibrate_gq_segmental_dups_index',
    'recalibrate_gq_simple_reps_index',
    'recalibrate_gq_umap_s100_index',
    'recalibrate_gq_umap_s24_index',
]
recalibrate_gq_args = [
    '--keep-homvar false',
    '--keep-homref true',
    '--keep-multiallelic true',
    '--skip-genotype-filtering true',
    '--min-samples-to-estimate-allele-frequency -1',
]

# FilterGenotypes - stringent end of [0.3, 0.5] range
fmax_beta = 0.3

sl_filter_args = '--small-del-threshold 93 --medium-del-threshold 100 --small-dup-threshold -51 --medium-dup-threshold -4 --ins-threshold -13 --inv-threshold -19'
noncoding_bed = 'gs://cpg-common-main/references/gatk-sv/hg38/v0/sv-resources/resources/v1/noncoding.sort.hg38.bed'

[elasticsearch]
# Configure access to ElasticSearch server
port = '9243'
host = 'elasticsearch.es.australia-southeast1.gcp.elastic-cloud.com'
username = 'seqr'
# Load ElasticSearch password from a secret, unless SEQR_ES_PASSWORD is set
password_secret_id = 'seqr-es-password'
password_project_id = 'seqr-308602'
