[workflow]
name = 'gatk_sv'
dataset_gcp_project = 'seqr-308602'
dataset = 'seqr'
ref_fasta = 'gs://cpg-common-main/references/hg38/v0/dragen_reference/Homo_sapiens_assembly38_masked.fasta'

# switches to deactivate all Metrics workflows
# "GatherBatchEvidenceMetrics and the other metrics routines at the end of the main workflows are
# primarily for development and testing purposes, so you don’t need to run them as a user"
# https://centrepopgen.slack.com/archives/C02E83V5JSF/p1705547576042719

# these metrics workflows are typically running svtest (https://github.com/broadinstitute/gatk-sv/blob/d37e453038e425acba9683da503218fe3d4b1033/src/svtest/setup.py)
# on each output of the stage, producing output files containing a count/distribution of different variants
# and sizes. The workflow files we use do not (and can not) copy these result files into permanent storage, so
# even if we run them, we will lose the results
[resource_overrides.GatherBatchEvidence]
# defaults to false due to runtime/expense
run_matrix_qc = false
run_module_metrics = false

[resource_overrides.ClusterBatch]
run_module_metrics = false

[resource_overrides.GenerateBatchMetrics]
run_module_metrics = false

[resource_overrides.FilterBatch]
run_module_metrics = false

[resource_overrides.GenotypeBatch]
run_module_metrics = false
