[workflow]
name = 'long_read_snps_indels_annotation'
ref_fasta = 'gs://cpg-common-main/references/hg38/v0/dragen_reference/Homo_sapiens_assembly38_masked.fasta'
status_reporter = 'metamist'
vep_version = '110'