[workflow]
name = 'mini_annotation'
sequencing_type = 'exome'

[annotations]
echtvar = "gs://cpg-common-test-analysis/gnomad/echtvar/gnomad_4.1_echtvar.zip"
gff3 = "gs://cpg-common-test-analysis/talos/GRCh38.gff3.gz"
region = "gs://cpg-common-test-analysis/talos/38.bed"

[images]
# todo replace with main image
echtvar = 'australia-southeast1-docker.pkg.dev/cpg-common/images-dev/echtvar:v0.2.1'
