[workflow]
name = 'mini_annotation'
sequencing_type = 'exome'

[annotations]
echtvar = "gs://cpg-common-test-analysis/gnomad/echtvar/gnomad_4.1_echtvar.zip"
mane_release = "1.4"
mane_url = "https://ftp.ncbi.nlm.nih.gov/refseq/MANE/MANE_human/release_{}/MANE.GRCh38.v{}.summary.txt.gz"
ensembl_version = "113"
ensembl_url = "https://ftp.ensembl.org/pub/release-{}/gff3/homo_sapiens/Homo_sapiens.GRCh38.{}.gff3.gz"
