[workflow]
sequencing_type = "transcriptome"

[trim]
adapter_type = "ILLUMINA_TRUSEQ"

[references.star]
gtf = 'gs://cpg-common-main/references/star/hg38/hg38.gtf'
fasta = "gs://cpg-common-main/references/star/hg38/hg38.fa"
