[workflow]
name = 'seqr_loader_long_read'
dataset_gcp_project = 'seqr-308602'
status_reporter = 'metamist'

[workflow.bam_to_cram]
analysis_type = 'pacbio_cram'

[resource_overrides.bam_to_cram]
nthreads = 1
storage_gb = 50
