[workflow]
name = 'seqr_loader_long_read'
dataset_gcp_project = 'seqr-308602'
status_reporter = 'metamist'

# update this when cpg_workflows.scripts.get_gencode_gtf.sh is re-run
gencode_gtf_file = 'gs://cpg-common-main/references/hg38/v0/gencode_47.gtf.gz'

[workflow.bam_to_cram]
analysis_type = 'pacbio_cram'

[workflow.long_read_vcf_annotation]
pipeface_versions = ['v0.6.1']

[resource_overrides.bam_to_cram]
nthreads = 1
storage_gb = 50
