[workflow]
name = "talos_prep"

mane_version = "1.4"
ensembl_version = "113"

[annotations]
# this currently contains the gnomAD v4.1 genomes-only data
echtvar = "gs://cpg-common-main/gnomad/echtvar/gnomad_4.1_whole_genome.zip"
