[workflow]
name = 'talos_prep'

mane_version = "1.4"
ensembl_version = "113"

[annotations]
echtvar = "gs://cpg-common-main-analysis/gnomad/echtvar/gnomad_4.1_whole_genome.zip"
alphamissense_tar = "gs://cpg-common-main/references/alphamissense/alphamissense_38.ht.tar.gz"
