[workflow]
name = "talos_prep"

mane_version = "1.4"
ensembl_version = "113"

[annotations]
# this contains the gnomad exomes & genomes data
echtvar = "gs://cpg-common-main/gnomad/echtvar/gnomad_4.1_region_merged_GRCh38_whole_genome.zip"
