[workflow]
sequencing_type = 'genome'
vep_image = '110.1-1'
vep_version = '110'

[vep]
scatter_count = 50

[references]
vep_105_mount = "gs://cpg-common-main/references/vep/105.0/mount"
vep_110_mount = "gs://cpg-common-main/references/vep/110/mount"
