[workflow]
sequencing_type = 'genome'
vep_version = '110'

[vep]
scatter_count = 1

[images]
vep_110 = "australia-southeast1-docker.pkg.dev/cpg-common/images/ensembl-vep:release_110.1"

[references]
vep_105_mount = "gs://cpg-common-main/references/vep/105.0/mount"
vep_110_mount = "gs://cpg-common-main/references/vep/110/mount"