[workflow]
only_stages = ['GenotypeBatch']
# this will be a single VCF, combined across multiple sub-cohort VCF outputs
cohort_depth_vcf = 'gs://cpg-seqr-main/gatk_sv/147795b8125006e53b8f0a164f079f2efe2cd7_993/MergeBatchSites/cohort_depth.vcf.gz'
cohort_pesr_vcf = 'gs://cpg-seqr-main/gatk_sv/147795b8125006e53b8f0a164f079f2efe2cd7_993/MergeBatchSites/cohort_pesr.vcf.gz'
