[storage.default]
default = "gs://acute-care-test"
web = "gs://cpg-acute-care-test-web"
analysis = "gs://cpg-acute-care-test-analysis"
tmp = "gs://cpg-acute-care-test-tmp"
web_url = "https://test-web.populationgenomics.org.au/acute-care"

[storage.acute-care]
default = "gs://cpg-acute-care-test"
web = "gs://cpg-acute-care-test-web"
analysis = "gs://cpg-acute-care-test-analysis"
tmp = "gs://cpg-acute-care-test-tmp"
web_url = "https://test-web.populationgenomics.org.au/acute-care"

[workflow]
image_registry_prefix = "australia-southeast1-docker.pkg.dev/cpg-common/images"
reference_prefix = "gs://cpg-reference"
web_url_template = "https://test-web.populationgenomics.org.au/acute-care"
skip_samples_with_missing_input = true
check_inputs = true
check_intermediates = true
check_expected_outputs = true
name = "large_cohort"
scatter_count = 5
access_level = "test"
dataset = "acute-care"
dataset_gcp_project = "acute-care"
driver_image = "australia-southeast1-docker.pkg.dev/analysis-runner/images/driver:5f6536ce7828bf06973333bcd7a1e366962f06ee-hail-5ed7ce7a5694434e2b945acaf64a7a7573dc175f"
output_prefix = "acute-care"
sequencing_type = "genome"
input_datasets = [ "acute-care",]
output_version = "0.1"

[images]
gatk = "gatk:4.2.6.1"
bcftools = "bcftools:1.16"
bwa = "bwa:v0"
bwamem2 = "bwamem2:v0"
dragmap = "dragmap:1.3.0"
samtools = "picard_samtools:v0"
picard = "picard_samtools:v0"
picard_samtools = "picard_samtools:v0"
somalier = "somalier:v0.2.15"
peddy = "peddy:v0"
vep = "vep:105.0"
verifybamid = "verifybamid:2.0.1"
multiqc = "multiqc:v1.12"
fastqc = "fastqc:v0.11.9_cv8"
cpg_workflows = "cpg_workflows:latest"
stripy = "stripy:v2.2"

[references]
genome_build = "GRCh38"
somalier_sites = "somalier/v0/sites.hg38.vcf.gz"
somalier_1kg_targz = "somalier/v0/1kg.somalier.tar.gz"
somalier_1kg_labels = "somalier/v0/ancestry-labels-1kg.tsv"
vep_mount = "vep/105.0/mount"
liftover_38_to_37 = "liftover/grch38_to_grch37.over.chain.gz"
gencode_gtf = "gencode/gencode.v39.annotation.gtf.bgz"

[hail]
delete_scratch_on_exit = false
pool_label = "large-cohort"
billing_project = "acute-care"
bucket = "cpg-acute-care-hail"
dry_run=true

[vqsr]
snp_filter_level = 99.7
indel_filter_level = 99.0

[large_cohort]
min_pop_prob = 0.5
max_kin = 0.2
n_pcs = 16
pop_meta_field = "Superpopulation name"

[images.hap]
py = "hap.py:v0.3.15"

[references.broad]
prefix = "hg38/v0"
dragmap_prefix = "dragen_reference"
ref_fasta = "dragen_reference/Homo_sapiens_assembly38_masked.fasta"
noalt_bed = "sv-resources/resources/v1/primary_contigs_plus_mito.bed.gz"
exome_bed = "Homo_sapiens_assembly38.contam.exome_calling_regions.v1.bed"
genome_calling_interval_lists = "wgs_calling_regions.hg38.interval_list"
exome_calling_interval_lists = "exome_calling_regions.v1.interval_list"
genome_evaluation_interval_lists = "wgs_evaluation_regions.hg38.interval_list"
exome_evaluation_interval_lists = "exome_evaluation_regions.v1.interval_list"
genome_coverage_interval_list = "wgs_coverage_regions.hg38.interval_list"
dbsnp_vcf = "Homo_sapiens_assembly38.dbsnp138.vcf"
dbsnp_vcf_index = "Homo_sapiens_assembly38.dbsnp138.vcf.idx"
hapmap_vcf = "hapmap_3.3.hg38.vcf.gz"
hapmap_vcf_index = "hapmap_3.3.hg38.vcf.gz.tbi"
omni_vcf = "1000G_omni2.5.hg38.vcf.gz"
omni_vcf_index = "1000G_omni2.5.hg38.vcf.gz.tbi"
one_thousand_genomes_vcf = "1000G_phase1.snps.high_confidence.hg38.vcf.gz"
one_thousand_genomes_vcf_index = "1000G_phase1.snps.high_confidence.hg38.vcf.gz.tbi"
mills_vcf = "Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
mills_vcf_index = "Mills_and_1000G_gold_standard.indels.hg38.vcf.gz.tbi"
axiom_poly_vcf = "Axiom_Exome_Plus.genotypes.all_populations.poly.hg38.vcf.gz"
axiom_poly_vcf_index = "Axiom_Exome_Plus.genotypes.all_populations.poly.hg38.vcf.gz.tbi"
genome_contam_ud = "contamination-resources/1000g/1000g.phase3.100k.b38.vcf.gz.dat.UD"
genome_contam_bed = "contamination-resources/1000g/1000g.phase3.100k.b38.vcf.gz.dat.bed"
genome_contam_mu = "contamination-resources/1000g/1000g.phase3.100k.b38.vcf.gz.dat.mu"
exome_contam_ud = "contamination-resources/1000g/whole_exome_illumina_coding_v1.Homo_sapiens_assembly38.1000g.contam.UD"
exome_contam_bed = "contamination-resources/1000g/whole_exome_illumina_coding_v1.Homo_sapiens_assembly38.1000g.contam.bed"
exome_contam_mu = "contamination-resources/1000g/whole_exome_illumina_coding_v1.Homo_sapiens_assembly38.1000g.contam.mu"

[references.gnomad]
prefix = "gnomad/v0"
tel_and_cent_ht = "telomeres_and_centromeres/hg38.telomeresAndMergedCentromeres.ht"
lcr_intervals_ht = "lcr_intervals/LCRFromHengHg38.ht"
seg_dup_intervals_ht = "seg_dup_intervals/GRCh38_segdups.ht"
clinvar_ht = "clinvar/clinvar_20190923.ht"
hapmap_ht = "hapmap/hapmap_3.3.hg38.ht"
kgp_omni_ht = "kgp/1000G_omni2.5.hg38.ht"
kgp_hc_ht = "kgp/1000G_phase1.snps.high_confidence.hg38.ht"
mills_ht = "mills/Mills_and_1000G_gold_standard.indels.hg38.ht"
predetermined_qc_variants = "sample_qc/pre_ld_pruning_qc_variants.ht"

[references.seqr]
prefix = "seqr/v0-1"
combined_reference = "combined_reference_data_grch38-2.0.4.ht"
clinvar = "clinvar.GRCh38.ht"

[references.validation]
prefix = "validation"

[validation.sample_map]
HG001_NA12878 = "HG001"
SYNDIP = "syndip"

[large_cohort.sample_qc_cutoffs]
min_coverage = 18
max_n_snps = 8000000
min_n_snps = 2400000
max_n_singletons = 800000
max_r_duplication = 0.3
max_r_het_hom = 3.3

[references.validation.syndip]
truth = "syndip/truth/full.38.20180222.vcf.gz"
regions = "syndip/regions/syndip.b38_20180222.bed"

[references.validation.HG001]
truth = "giab/truth/HG001_GRCh38_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf_PGandRTGphasetransfer.vcf.gz"
regions = "giab/regions/HG001_GRCh38_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf_nosomaticdel_noCENorHET7.bed"
