[workflow]
dataset_gcp_project = 'acute-care-321904'
dataset = 'acute-care'
datasets = ['acute-care']
access_level = 'full'
check_expected_outputs = false

[hail]
billing_project = 'acute-care'

[references.broad]
bwa_ref_fasta = 'Homo_sapiens_assembly38.fasta'
