[workflow]
input_datasets = ['acute-care']
access_level = 'test'
only_samples = [
    'CPG202994',
    'CPG203000',
    'CPG203018',
    'CPG203034',
    'CPG203042',
    'CPG203075',
    'CPG203067',
    'CPG203026',
    'CPG203059',
]
skip_qc = true
check_expected_outputs = false

[references.broad]
bwa_ref_fasta = 'Homo_sapiens_assembly38.fasta'
