[workflow]
dataset_gcp_project = 'acute-care-321904'
dataset = 'acute-care'
input_datasets = ['acute-care']
access_level = 'test'
only_samples = [
    'CPG202994',
    'CPG203000',
    'CPG203018',
    'CPG203034',
    'CPG203042',
    'CPG203075',
    'CPG203067',
    'CPG203026',
    'CPG203059',
]

[hail]
billing_project = 'acute-care'

[references.broad]
bwa_ref_fasta = 'Homo_sapiens_assembly38.fasta'
