[workflow]
input_datasets = ['bioheart']
sequencing_type = 'genome'

# leave this to true, since one sample doesn't have sequencing data
skip_samples_with_missing_input = true

output_version = '0.1'
