[workflow]
show_workflow = true
check_inputs = true
skip_samples_with_missing_input = false
check_intermediates = true
check_expected_outputs = true
reblock_gq_bands = [20, 30, 40]
name = "large_cohort"
scatter_count = 20
status_reporter = "metamist"
access_level = "test"
dataset = "thousand-genomes"
dataset_gcp_project = "thousand-genomes"
driver_image = "australia-southeast1-docker.pkg.dev/cpg-common/images/cpg_workflows:latest"
output_prefix = "force-rerun"
sequencing_type = "genome"
last_stages = ["CramMultiQC"]
force_stages = ["CramQC", "CramMultiQC"]
output_version = "1.0"
skip_samples = ["CPG88088", "CPG88435"]
ref_fasta = "gs://cpg-common-main/references/hg38/v0/Homo_sapiens_assembly38.fasta"

[hail]
dry_run = true
delete_scratch_on_exit = false
pool_label = "large-cohort"
billing_project = "thousand-genomes"
bucket = "cpg-thousand-genomes-hail"

[vqsr]
snp_filter_level = 99.7
indel_filter_level = 99.0

[large_cohort]
max_kin = 0.12
n_pcs = 16
min_pop_prob = 0.5
pop_meta_field = "Superpopulation name"

[references]
genome_build = "GRCh38"
vep_mount = "gs://cpg-common-main/references/vep/105.0/mount"
liftover_38_to_37 = "gs://cpg-common-main/references/liftover/grch38_to_grch37.over.chain.gz"
somalier_sites = "gs://cpg-common-main/references/somalier/sites.hg38.vcf.gz"
seqr_combined_reference_data = "gs://cpg-common-main/references/seqr/v0/combined_reference_data_grch38.ht"
seqr_clinvar = "gs://cpg-common-main/references/seqr/v0/clinvar.GRCh38.ht"

[infrastructure]
members_cache_location = "gs://cpg-members-group-cache"

[images]
bcftools = "australia-southeast1-docker.pkg.dev/cpg-common/images/bcftools:1.16"
bedtools = "australia-southeast1-docker.pkg.dev/cpg-common/images/bedtools:2.30.0"
cellregmap = "australia-southeast1-docker.pkg.dev/cpg-common/images/cellregmap:0.0.3"
dragmap = "australia-southeast1-docker.pkg.dev/cpg-common/images/dragmap:1.3.0"
expansionhunter = "australia-southeast1-docker.pkg.dev/cpg-common/images/expansionhunter:5.0.0"
fastqc = "australia-southeast1-docker.pkg.dev/cpg-common/images/fastqc:0.11.9"
gatk = "australia-southeast1-docker.pkg.dev/cpg-common/images/gatk:4.2.6.1"
hap-py = "australia-southeast1-docker.pkg.dev/cpg-common/images/hap-py:0.3.15"
multipy = "australia-southeast1-docker.pkg.dev/cpg-common/images/multipy:0.16"
multiqc = "australia-southeast1-docker.pkg.dev/cpg-common/images/multiqc:1.14"
peer = "australia-southeast1-docker.pkg.dev/cpg-common/images/peer:1.3"
picard = "australia-southeast1-docker.pkg.dev/cpg-common/images/picard:2.27.4"
reviewer = "australia-southeast1-docker.pkg.dev/cpg-common/images/reviewer:0.2.7"
saige-qtl = "australia-southeast1-docker.pkg.dev/cpg-common/images/saige-qtl:1bdfe8408a17f7da8b0453a697a867f412f48bcc"
samblaster = "australia-southeast1-docker.pkg.dev/cpg-common/images/samblaster:0.1.26"
samtools = "australia-southeast1-docker.pkg.dev/cpg-common/images/samtools:1.16.1"
somalier = "australia-southeast1-docker.pkg.dev/cpg-common/images/somalier:0.2.15"
trtools = "australia-southeast1-docker.pkg.dev/cpg-common/images/trtools:4.0.2"
vep = "australia-southeast1-docker.pkg.dev/cpg-common/images/vep:105.0"
verifybamid = "australia-southeast1-docker.pkg.dev/cpg-common/images/verifybamid:2.0.1"
stripy = "australia-southeast1-docker.pkg.dev/cpg-common/images/stripy:2.2"
gangstr = "australia-southeast1-docker.pkg.dev/cpg-common/images/gangstr:2.5.0"
hipstr = "australia-southeast1-docker.pkg.dev/cpg-common/images/hipstr:v0.6.2"
bgt = "australia-southeast1-docker.pkg.dev/cpg-common/images/bgt:v1.0"
cpg_workflows = "australia-southeast1-docker.pkg.dev/cpg-common/images/cpg_workflows:1.12.4"

[large_cohort.sample_qc_cutoffs]
min_coverage = 18
max_n_snps = 8000000
min_n_snps = 2400000
max_n_singletons = 800000
max_r_duplication = 0.3
max_r_het_hom = 3.3

[references.gnomad]
tel_and_cent_ht = "gs://cpg-common-main/references/gnomad/v0/telomeres_and_centromeres/hg38.telomeresAndMergedCentromeres.ht"
predetermined_qc_variants = "gs://cpg-common-main/references/gnomad/v0/sample_qc/pre_ld_pruning_qc_variants.ht"
lcr_intervals_ht = "gs://cpg-common-main/references/gnomad/v0/lcr_intervals/LCRFromHengHg38.ht"
seg_dup_intervals_ht = "gs://cpg-common-main/references/gnomad/v0/seg_dup_intervals/GRCh38_segdups.ht"
clinvar_ht = "gs://cpg-common-main/references/gnomad/v0/clinvar/clinvar_20190923.ht"
hapmap_ht = "gs://cpg-common-main/references/gnomad/v0/hapmap/hapmap_3.3.hg38.ht"
kgp_omni_ht = "gs://cpg-common-main/references/gnomad/v0/kgp/1000G_omni2.5.hg38.ht"
kgp_hc_ht = "gs://cpg-common-main/references/gnomad/v0/kgp/1000G_phase1.snps.high_confidence.hg38.ht"
mills_ht = "gs://cpg-common-main/references/gnomad/v0/mills/Mills_and_1000G_gold_standard.indels.hg38.ht"

[references.broad]
dragmap_prefix = "gs://cpg-common-main/references/hg38/v0/dragen_reference"
ref_fasta = "gs://cpg-common-main/references/hg38/v0/dragen_reference/Homo_sapiens_assembly38_masked.fasta"
noalt_bed = "gs://cpg-common-main/references/hg38/v0/sv-resources/resources/v1/primary_contigs_plus_mito.bed.gz"
genome_calling_interval_lists = "gs://cpg-common-main/references/hg38/v0/wgs_calling_regions.hg38.interval_list"
exome_calling_interval_lists = "gs://cpg-common-main/references/hg38/v0/exome_calling_regions.v1.interval_list"
genome_evaluation_interval_lists = "gs://cpg-common-main/references/hg38/v0/wgs_evaluation_regions.hg38.interval_list"
exome_evaluation_interval_lists = "gs://cpg-common-main/references/hg38/v0/exome_evaluation_regions.v1.interval_list"
genome_coverage_interval_list = "gs://cpg-common-main/references/hg38/v0/wgs_coverage_regions.hg38.interval_list"
unpadded_intervals_file = "gs://cpg-common-main/references/hg38/v0/hg38.even.handcurated.20k.intervals"
dbsnp_vcf = "gs://cpg-common-main/references/hg38/v0/Homo_sapiens_assembly38.dbsnp138.vcf"
dbsnp_vcf_index = "gs://cpg-common-main/references/hg38/v0/Homo_sapiens_assembly38.dbsnp138.vcf.idx"
hapmap_vcf = "gs://cpg-common-main/references/hg38/v0/hapmap_3.3.hg38.vcf.gz"
hapmap_vcf_index = "gs://cpg-common-main/references/hg38/v0/hapmap_3.3.hg38.vcf.gz.tbi"
omni_vcf = "gs://cpg-common-main/references/hg38/v0/1000G_omni2.5.hg38.vcf.gz"
omni_vcf_index = "gs://cpg-common-main/references/hg38/v0/1000G_omni2.5.hg38.vcf.gz.tbi"
one_thousand_genomes_vcf = "gs://cpg-common-main/references/hg38/v0/1000G_phase1.snps.high_confidence.hg38.vcf.gz"
one_thousand_genomes_vcf_index = "gs://cpg-common-main/references/hg38/v0/1000G_phase1.snps.high_confidence.hg38.vcf.gz.tbi"
mills_vcf = "gs://cpg-common-main/references/hg38/v0/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
mills_vcf_index = "gs://cpg-common-main/references/hg38/v0/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz.tbi"
axiom_poly_vcf = "gs://cpg-common-main/references/hg38/v0/Axiom_Exome_Plus.genotypes.all_populations.poly.hg38.vcf.gz"
axiom_poly_vcf_index = "gs://cpg-common-main/references/hg38/v0/Axiom_Exome_Plus.genotypes.all_populations.poly.hg38.vcf.gz.tbi"
genome_contam_ud = "gs://cpg-common-main/references/hg38/v0/contamination-resources/1000g/1000g.phase3.100k.b38.vcf.gz.dat.UD"
genome_contam_bed = "gs://cpg-common-main/references/hg38/v0/contamination-resources/1000g/1000g.phase3.100k.b38.vcf.gz.dat.bed"
genome_contam_mu = "gs://cpg-common-main/references/hg38/v0/contamination-resources/1000g/1000g.phase3.100k.b38.vcf.gz.dat.mu"
exome_contam_ud = "gs://cpg-common-main/references/hg38/v0/contamination-resources/1000g/whole_exome_illumina_coding_v1.Homo_sapiens_assembly38.1000g.contam.UD"
exome_contam_bed = "gs://cpg-common-main/references/hg38/v0/contamination-resources/1000g/whole_exome_illumina_coding_v1.Homo_sapiens_assembly38.1000g.contam.bed"
exome_contam_mu = "gs://cpg-common-main/references/hg38/v0/contamination-resources/1000g/whole_exome_illumina_coding_v1.Homo_sapiens_assembly38.1000g.contam.mu"
protein_coding_gtf = "gs://cpg-common-main/references/hg38/v0/sv-resources/resources/v1/MANE.GRCh38.v0.95.select_ensembl_genomic.gtf"

[references.gatk_sv]
wham_include_list_bed_file = "gs://cpg-common-main/references/gatk-sv/hg38/v0/sv-resources/resources/v1/wham_whitelist.bed"
primary_contigs_list = "gs://cpg-common-main/references/gatk-sv/hg38/v0/sv-resources/resources/v1/primary_contigs.list"
primary_contigs_fai = "gs://cpg-common-main/references/gatk-sv/hg38/v0/sv-resources/resources/v1/contig.fai"
preprocessed_intervals = "gs://cpg-common-main/references/gatk-sv/hg38/v0/sv-resources/resources/v1/preprocessed_intervals.interval_list"
manta_region_bed = "gs://cpg-common-main/references/gatk-sv/hg38/v0/sv-resources/resources/v1/primary_contigs_plus_mito.bed.gz"
melt_standard_vcf_header = "gs://cpg-common-main/references/gatk-sv/hg38/v0/sv-resources/resources/v1/melt_standard_vcf_header.txt"
genome_file = "gs://cpg-common-main/references/gatk-sv/hg38/v0/sv-resources/resources/v1/hg38.genome"
wgd_scoring_mask = "gs://cpg-common-main/references/gatk-sv/hg38/v0/sv-resources/resources/v1/wgd_scoring_mask.hg38.gnomad_v3.bed"
allosomal_contigs = "gs://cpg-common-main/references/gatk-sv/hg38/v0/sv-resources/resources/v1/allosome.fai"
contig_ploidy_priors = "gs://cpg-common-main/references/gatk-sv/hg38/v0/sv-resources/resources/v1/hg38.contig_ploidy_priors_homo_sapiens.tsv"
inclusion_bed = "gs://cpg-common-main/references/gatk-sv/hg38/v0/sv-resources/resources/v1/hg38_primary_contigs.bed"
autosome_file = "gs://cpg-common-main/references/gatk-sv/hg38/v0/sv-resources/resources/v1/autosome.fai"
allosome_file = "gs://cpg-common-main/references/gatk-sv/hg38/v0/sv-resources/resources/v1/allosome.fai"
cnmops_exclude_list = "gs://cpg-common-main/references/gatk-sv/hg38/v0/sv-resources/resources/v1/GRCh38_Nmask.bed"
cytoband = "gs://cpg-common-main/references/gatk-sv/hg38/v0/sv-resources/resources/v1/cytobands_hg38.bed.gz"
mei_bed = "gs://cpg-common-main/references/gatk-sv/hg38/v0/sv-resources/resources/v1/mei_hg38.bed.gz"
rmsk = "gs://cpg-common-main/references/gatk-sv/hg38/v0/sv-resources/resources/v1/randomForest_blacklist.withRepMask.bed.gz"
segdups = "gs://cpg-common-main/references/gatk-sv/hg38/v0/sv-resources/resources/v1/hg38.SD_gaps_Cen_Tel_Heter_Satellite_lumpy.blacklist.sorted.merged.bed.gz"
seed_cutoffs = "gs://cpg-common-main/references/gatk-sv/hg38/v0/sv-resources/resources/v1/seed_cutoff.txt"
pesr_exclude_list = "gs://cpg-common-main/references/gatk-sv/hg38/v0/sv-resources/resources/v1/PESR.encode.peri_all.repeats.delly.hg38.blacklist.sorted.bed.gz"
depth_exclude_list = "gs://cpg-common-main/references/gatk-sv/hg38/v0/sv-resources/resources/v1/depth_blacklist.sorted.bed.gz"
bin_exclude = "gs://cpg-common-main/references/gatk-sv/hg38/v0/sv-resources/resources/v1/bin_exclude.hg38.gatkcov.bed.gz"
empty_file = "gs://cpg-common-main/references/gatk-sv/hg38/v0/sv-resources/resources/v1/empty.file"
protein_coding_gtf = "gs://cpg-common-main/references/gatk-sv/hg38/v0/sv-resources/resources/v1/MANE.GRCh38.v0.95.select_ensembl_genomic.gtf"
ped_file = "gs://cpg-common-main/references/gatk-sv/hg38/v0/sv-resources/ref-panel/1KG/v1/ped/1kg_ref_panel_v1.ped"
clean_vcf = "gs://cpg-common-main/references/gatk-sv/hg38/v0/sv-resources/ref-panel/1KG/v1/calls/ref_panel_1kg_v1.cleaned.vcf.gz"
ref_panel_bincov_matrix = "gs://cpg-common-main/references/gatk-sv/hg38/v0/sv-resources/ref-panel/1KG/v1/merged_evidence/ref_panel_1kg_v1.bincov.bed.gz"
qc_definitions = "gs://cpg-common-main/references/gatk-sv/hg38/v0/sv-resources/ref-panel/1KG/v2/single_sample.qc_definitions.tsv"
contig_ploidy_model_tar = "gs://cpg-common-main/references/gatk-sv/hg38/v0/sv-resources/ref-panel/1KG/v2/gcnv/ref_panel_1kg_v2-contig-ploidy-model.tar.gz"
model_tar_tmpl = "gs://cpg-common-main/references/gatk-sv/hg38/v0/sv-resources/ref-panel/1KG/v2/gcnv/model_files/ref_panel_1kg_v2-gcnv-model-shard-{shard}.tar.gz"
ref_panel_PE_file_tmpl = "gs://cpg-common-main/references/gatk-sv/hg38/v0/sv-resources/ref-panel/tws_SVEvidence/pe/{sample}.pe.txt.gz"
ref_panel_SR_file_tmpl = "gs://cpg-common-main/references/gatk-sv/hg38/v0/sv-resources/ref-panel/tws_SVEvidence/sr/{sample}.sr.txt.gz"
ref_panel_SD_file_tmpl = "gs://cpg-common-main/references/gatk-sv/hg38/v0/sv-resources/ref-panel/tws_SVEvidence/sd/{sample}.sd.txt.gz"

[references.syndip]
truth_vcf = "gs://cpg-common-main/references/validation/syndip/full.38.20180222.vcf.gz"
regions_bed = "gs://cpg-common-main/references/validation/syndip/syndip.b38_20180222.bed"
truth_mt = "gs://cpg-common-main/references/validation/syndip/syndip.b38_20180222.mt"
regions_ht = "gs://cpg-common-main/references/validation/syndip/syndip_b38_20180222_hc_regions.ht"

[references.na12878]
truth_vcf = "gs://cpg-common-main/references/validation/na12878/HG001_GRCh38_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf_PGandRTGphasetransfer.vcf.gz"
regions_bed = "gs://cpg-common-main/references/validation/na12878/HG001_GRCh38_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf_nosomaticdel_noCENorHET7.bed"
truth_mt = "gs://cpg-common-main/references/validation/na12878/HG001_GRCh38_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf_PGandRTGphasetransfer.mt"
regions_ht = "gs://cpg-common-main/references/validation/na12878/HG001_GRCh38_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf_nosomaticdel_noCENorHET7_hc_regions.ht"

[validation.sample_map]
HG001_NA12878 = "na12878"
SYNDIP = "syndip"

[storage.default]
default = "gs://cpg-thousand-genomes-test"
web = "gs://cpg-thousand-genomes-test-web"
analysis = "gs://cpg-thousand-genomes-test-analysis"
tmp = "gs://cpg-thousand-genomes-test-tmp"
upload = "gs://cpg-thousand-genomes-test-upload"
web_url = "https://test-web.populationgenomics.org.au/thousand-genomes"

[storage.thousand-genomes]
default = "gs://cpg-thousand-genomes-test"
web = "gs://cpg-thousand-genomes-test-web"
analysis = "gs://cpg-thousand-genomes-test-analysis"
tmp = "gs://cpg-thousand-genomes-test-tmp"
upload = "gs://cpg-thousand-genomes-test-upload"
web_url = "https://test-web.populationgenomics.org.au/thousand-genomes"
