[workflow]
#dataset_gcp_project = 'acute-care-321904'
#dataset = 'acute-care'
input_datasets = ['broad-rgp']
access_level = 'test'

# CRAMs were aligned using an unmasked reference: 
# gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta
# we need to use the same reference to access CRAMs.
# EDIT the above comment is completely wrong?
# see https://github.com/populationgenomics/production-pipelines/issues/206
# see https://github.com/populationgenomics/production-pipelines/issues/208

# Genomes were aligned using a masked reference, check with
# export GCS_OAUTH_TOKEN=$(gcloud auth application-default print-access-token)
# samtools view -H gs://cpg-acute-care-test/cram/CPG262543.cram | less
ref_fasta = 'gs://cpg-common-main/references/hg38/v0/dragen_reference/Homo_sapiens_assembly38_masked.fasta'

#[hail]
#billing_project = 'acute-care'

[images]
cloud_sdk_docker = "australia-southeast1-docker.pkg.dev/cpg-common/images/sv/cloud-sdk"
cnmops_docker = "australia-southeast1-docker.pkg.dev/cpg-common/images/cnmops:v0.27.0"
cnmops_virtual_env = "australia-southeast1-docker.pkg.dev/cpg-common/images/cnmops-virtual-env:v0.27.0"
gatk_docker = 'australia-southeast1-docker.pkg.dev/cpg-common/images/sv/gatk:4.2.6.1-36-g88b0578'
gatk_docker_pesr_override = 'australia-southeast1-docker.pkg.dev/cpg-common/images/sv/gatk:4.2.6.1-36-g88b0578'
genomes_in_the_cloud_docker = 'australia-southeast1-docker.pkg.dev/cpg-common/images/sv/genomes-in-the-cloud:2.3.2-1510681135'
manta_docker = 'australia-southeast1-docker.pkg.dev/cpg-common/images/sv/manta:8645aa'
samtools_cloud_docker = "australia-southeast1-docker.pkg.dev/cpg-common/images/samtools-cloud:v0.27.0"
samtools_cloud_virtual_env = "australia-southeast1-docker.pkg.dev/cpg-common/images/samtools-cloud-virtual-env:v0.27.0"
scramble_docker = 'australia-southeast1-docker.pkg.dev/cpg-common/images/sv/scramble:1.0.2'
sv_base_mini_docker = "australia-southeast1-docker.pkg.dev/cpg-common/images/sv-base-mini:v0.27.0"
sv_base_virtual_env = "australia-southeast1-docker.pkg.dev/cpg-common/images/sv-base-virtual-env:v0.27.0"
sv_pipeline_virtual_env = "australia-southeast1-docker.pkg.dev/cpg-common/images/sv-pipeline-virtual-env:v0.27.0"
sv_utils_env = "australia-southeast1-docker.pkg.dev/cpg-common/images/sv-utils-env:v0.27.0"
sv_base = "australia-southeast1-docker.pkg.dev/cpg-common/images/sv-base:v0.27.0"
sv_utils = "australia-southeast1-docker.pkg.dev/cpg-common/images/sv-utils:v0.27.0"
sv_pipeline_base_docker = "australia-southeast1-docker.pkg.dev/cpg-common/images/sv-pipeline:v0.27.0"
sv_pipeline_docker = "australia-southeast1-docker.pkg.dev/cpg-common/images/sv-pipeline:v0.27.0"
wham_docker = 'australia-southeast1-docker.pkg.dev/cpg-common/images/sv/wham:8645aa'
