[workflow]
dataset_gcp_project = 'acute-care-321904'
dataset = 'acute-care'
input_datasets = ['acute-care']
access_level = 'test'
only_samples = [
    'CPG202994',
    'CPG203000',
    'CPG203018',
    'CPG203034',
    'CPG203042',
    'CPG203075',
    'CPG203067',
    'CPG203026',
    'CPG203059',
]

# CRAMs were aligned using an unmasked reference: 
# gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta
# we need to use the same reference to access CRAMs.
ref_fasta = 'gs://cpg-reference/hg38/v0/Homo_sapiens_assembly38.fasta'

[hail]
billing_project = 'acute-care'
