[workflow]
dataset_gcp_project = 'hgdp-323802'
dataset = 'hgdp'
sequencing_type = 'genome'
scatter_count = 20
# first_stages = ['Combiner']
last_stages = ['SampleQC','Frequencies']
output_version = '1.0'
skip_qc = true

# CRAMs were aligned using an unmasked reference: 
# gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta
# we need to use the same reference to access CRAMs.
ref_fasta = 'gs://cpg-common-main/references/hg38/v0/Homo_sapiens_assembly38.fasta'

[hail]
billing_project = 'hgdp'
