[workflow]
last_stage = 'Genotype'
skip_samples = [
  'CPG216275',  # https://batch.hail.populationgenomics.org.au/batches/74382
  'CPG216010',  # https://batch.hail.populationgenomics.org.au/batches/74382
]

input_datasets = ['prophecy']
sequencing_type = 'genome'
access_level = 'full'
dataset = 'prophecy'
dataset_gcp_project = 'prophecy-339301'

[hail]
pool_label = 'large-cohort'
billing_project = 'prophecy'
