[workflow]
input_datasets = ['prophecy']
sequencing_type = 'genome'

skip_samples = [
  'CPG216010',  # replaced by CPG262915
  'CPG241299',  # Replaced by CPG262907
]
skip_stages = ['SomalierPedigree']
skip_samples_with_missing_input = true
highmem_workers = true

scatter_count = 20
output_version = '1.1'

[large_cohort.pca_background]
datasets = ['gs://cpg-common-main/references/ancestry/oceania_eur.mt']
pop_field = 'continental_pop'
