[workflow]
input_datasets = ['prophecy']
sequencing_type = 'genome'
access_level= 'test'

skip_samples = [
  'CPG216010',  # replaced by CPG262915
  'CPG241299',  # Replaced by CPG262907
]
skip_stages = ['SomalierPedigree']
first_stages = ['AncestryPlots']
last_stages=['AncestryPlots']
skip_samples_with_missing_input = true
highmem_workers = true

scatter_count = 20
output_version = '1.1'

[large_cohort.pca_background]
datasets = ['gs://cpg-hgdp-test/vds/1-0.vds/']
metadata_table = 'gs://cpg-hgdp-test/large_cohort/1-0/sample_qc.ht'
