[workflow]
input_datasets = ['prophecy']
sequencing_type = 'genome'

skip_samples = [
  'CPG216010',  # replaced by CPG262915
  'CPG241299',  # Replaced by CPG262907
]
skip_stages = ['SomalierPedigree']
skip_samples_with_missing_input = true
highmem_workers = true

scatter_count = 20
output_version = '1.1'
