[workflow]
input_datasets = ['prophecy']
sequencing_type = 'genome'

skip_samples = [
  'CPG216275',  # https://batch.hail.populationgenomics.org.au/batches/74382
  'CPG216010',  # https://batch.hail.populationgenomics.org.au/batches/74382
  'CPG241299',  # Replaced by CPG262907
]
skip_stages = ['SomalierPedigree']
skip_samples_with_missing_input = true
highmem_workers = true

# Process the following samples even if outputs exist, to handle replaced samples
force_samples = ['CPG243477', 'CPG217794', 'CPG216481', 'CPG214858']

scatter_count = 20
output_version = '0.1'
