[workflow]
input_datasets = ['prophecy']
sequencing_type = 'genome'

skip_samples = [
  'CPG216010',  # replaced by CPG262915
  'CPG241299',  # Replaced by CPG262907
]
skip_stages = ['SomalierPedigree', 'MakeSiteOnlyVcf', 'Vqsr','LoadVqsr']
first_stages = ['SampleQC']
last_stages=['SampleQC']
skip_samples_with_missing_input = true
highmem_workers = true
force_stages = ['SampleQC']

scatter_count = 20
output_version = '1.1'

[large_cohort.pca_background]
datasets = ['hgdp-1kg-test']

[large_cohort.pca_background.hgdp-1kg-test]
dataset_path = 'gs://cpg-hgdp-1kg-test/vds/v1-0.vds/'
metadata_table = ['gs://cpg-hgdp-test/large_cohort/1-0/sample_qc.ht', 'gs://cpg-thousand-genomes-test/large_cohort/1-0/sample_qc.ht/']
