[workflow]
first_stage = 'Align'
last_stage = 'Genotype'
only_samples = ['CPG243717']

datasets = ['validation']
create_es_index_for_datasets = ['validation']
check_inputs = false
check_intermediates = false
check_expected_outputs = false
