[workflow]
input_datasets = ['acute-care']
access_level = 'test'
only_samples = [
    'CPG202994',
    'CPG203000',
    'CPG203018',
    'CPG203042',
]
check_expected_outputs = true
check_intermediates = true

# CRAMs were aligned using an unmasked reference: 
# gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta
# we need to use the same reference to access CRAMs.
ref_fasta = 'gs://cpg-reference/hg38/v0/Homo_sapiens_assembly38.fasta'
