[workflow]
dataset_gcp_project = 'thousand-genomes'
dataset = 'thousand-genomes'
sequencing_type = 'genome'
scatter_count = 20
first_stages = ['Combiner']
last_stages = ['LoadVqsr', 'Frequencies']
skip_qc = true
output_version = '0.1'

[references.broad]
ref_fasta = 'Homo_sapiens_assembly38.fasta'

[hail]
billing_project = 'thousand-genomes'
