[workflow]
dataset_gcp_project = 'thousand-genomes'
dataset = 'thousand-genomes'
sequencing_type = 'genome'
scatter_count = 20

[references.broad]
ref_fasta = 'Homo_sapiens_assembly38.fasta'

[hail]
billing_project = 'thousand-genomes'
