[workflow]
input_datasets = ['validation']
create_es_index_for_datasets = ['validation']
skip_samples = [
    'CPG243717',  # NA12878_KCCG low coverage (8x)
]

check_inputs = false
check_intermediates = false
check_expected_outputs = false
