access_level = 'test'
input_dataset = [
    # seqr:
    'acute-care',
    'ag-hidden',
    'brain-malf',
    'circa',
    'epileptic-enceph',
    'flinders-ophthal',
    'heartkids',
    'hereditary-neuro',
    'ibmdx',
    'kidgen',
    'leukodystrophies',
    'mcri-lrp',
    'mito-disease',
    'ohmr3-mendelian',
    'ohmr4-epilepsy',
    'perth-neuro',
    'ravenscroft-arch',
    'ravenscroft-rdstudy',
    'rdnow',
    'rdp-kidney',
    'schr-neuro',
    'udn-aus-training',
    'validation',
    # large-cohort:
    'bioheart',
    'prophecy',
]
