name: Lint
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.10.2'

    - name: Install packages
      run: |
        pip install .
        pip install -r requirements-dev.txt

    - name: Install pre-commit
      run: |
        # Installing hooks
        pre-commit install --install-hooks

    - name: pre-commit
      run: pre-commit run --all-files
