name: Lint
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install packages
      run: |
        pip install .
        pip install -r requirements-dev.txt

    - name: Install pre-commit
      run: |
        # adding pylint section into pre-commit
        cat .github/workflows/pre-commit-config-pylint.yaml > .pre-commit-config-pylint.yaml
        pre-commit install --install-hooks

    - name: pre-commit
      run: pre-commit run --all-files
