name: Security Checks

on:
  workflow_dispatch:
  push:

jobs:
  pip-audit:
    runs-on: ubuntu-latest
    name: Pip Audit
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Setup build env
        run: |
          set -euxo pipefail

          pip install -r requirements-dev.txt
          pip install .
      - uses: pypa/gh-action-pip-audit@v1.1.0
        with:
          summary: true
