name: Test cohort
on:
  # Building on pull-requests, manual dispatch, and pushes to main; but restricting
  # publishing only to main pushes and manual dispatch with `if`s in specific steps.
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install
        run: pip install .[test,full]

      - name: Run unit tests
        run: python -m pytest test/test_cohort.py
