name: Test
on:
  # Building on pull-requests, manual dispatch, and pushes to main; but restricting
  # publishing only to main pushes and manual dispatch with `if`s in specific steps.
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install
        run: pip install .[test]

      - name: Run unit tests
        timeout-minutes: 20
        run: |
          PYTHONPATH=$PWD/gnomad_methods:$PWD/seqr-loading-pipelines \
          pytest test
