name: Test pipeline
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    env:
      GSA_KEY: ${{ secrets.GCP_SA_KEY }}
      HAIL_TOKEN: ${{ secrets.HAIL_TOKEN }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: gcloud setup
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: "fewgenomes"
          service_account_key: "${{ secrets.GCP_SA_KEY }}"

      - name: gcloud docker auth
        run: |
          gcloud auth configure-docker australia-southeast1-docker.pkg.dev

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test-env
          environment-file: environment-dev.yml
          channels: conda-forge,bioconda,defaults
          channel-priority: true
          python-version: 3.7

      - name: "Test pipelines"
        run: |
          python -m unittest tests/test_pipeline.py
