name: Test
on:
  # Building on pull-requests, manual dispatch, and pushes to main; but restricting
  # publishing only to main pushes and manual dispatch with `if`s in specific steps.
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        suffix:
          [
            #batch,
            #workflow,
            #cohort,
            #status,
            #large_cohort,
            seqr_loader_dry,
            #check_multiqc,
            #check_pedigree,
          ]
    steps:
      - uses: actions/checkout@main
        with:
          submodules: 'true'

      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install
        run: pip install .[test]

      - name: Debug
        continue-on-error: true
        run: |
          pip show aiodns aiohttp aiohttp_session google-auth hail pycares

      - name: Run unit tests
        timeout-minutes: 3
        run: |
          PYTHONPATH=$PWD/gnomad_methods:$PWD/seqr-loading-pipelines \
          python -m pytest -s test/test_${{ matrix.suffix }}.py
