name: Test pipeline
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain
      CLOUDSDK_CORE_DISABLE_PROMPTS: 1
      DOCKER_IMAGE: australia-southeast1-docker.pkg.dev/analysis-runner/images/driver:d9b6278802bd8f2e7c047848f625c6443c43c2a8-hail-0.2.73.devc6f6f09cec08
      GSA_KEY: ${{ secrets.GCP_SA_KEY }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: gcloud setup
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: "fewgenomes"
          service_account_key: "${{ secrets.GCP_SA_KEY }}"

      - name: gcloud docker auth
        run: |
          gcloud auth configure-docker australia-southeast1-docker.pkg.dev

      - name: "Test pipelines"
        run: |
          python -m unittest tests/test_pipeline.py
