name: Test
on:
  # Building on pull-requests, manual dispatch, and pushes to main; but restricting
  # publishing only to main pushes and manual dispatch with `if`s in specific steps.
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install
        run: pip install .[test]

      - name: Run unit tests
        timeout-minutes: 20
        run: |
          PYTHONPATH=$PWD/gnomad_methods:$PWD/seqr-loading-pipelines \
          coverage run -m pytest test

          rc=$?
          coverage xml

          echo "rc=$rc" >> $GITHUB_OUTPUT

      - name: "Upload coverage reports to Codecov"
        uses: codecov/codecov-action@v4.0.1
        with:
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
